/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hieu_myandroidnativeapp_Connect */

#ifndef _Included_com_hieu_myandroidnativeapp_Connect
#define _Included_com_hieu_myandroidnativeapp_Connect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hieu_myandroidnativeapp_Connect
 * Method:    nativeRecursive
 * Signature: (I)I
 */
jint Java_com_hieu_myandroidnativeapp_Connect_nativeRecursive
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
